#!/usr/bin/env python3
"""Generate the native Brother QL-580N CUPS PPD from physical media sizes."""

from decimal import Decimal
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "ppd" / "Brother-QL-580N-Native.ppd"
FILTER = "/Library/Printers/QL580NNative/rastertoql580n"
ICON = "/Library/Printers/QL580NNative/ql580n-native.icns"
CONTINUOUS_WIDTHS = (12, 29, 38, 50, 54, 62)
CONTINUOUS_LENGTHS = (30, 50, 100, 150, 200)
DIECUT_SIZES = ((17, 54), (17, 87), (23, 23), (29, 90),
                (38, 90), (39, 48), (52, 29), (62, 29), (62, 100))
DEFAULT_SIZE = "w62l50"


def points(mm) -> str:
    """Return a physical millimetre dimension in PostScript points."""
    value = Decimal(mm) * Decimal(72) / Decimal("25.4")
    return format(value.quantize(Decimal("0.00001")), "f")


def dots_mm(dots: int) -> Decimal:
    """Convert a 300 DPI printer offset to millimetres."""
    return Decimal(dots) * Decimal("25.4") / Decimal(300)


def media():
    for width in CONTINUOUS_WIDTHS:
        for length in CONTINUOUS_LENGTHS:
            yield f"w{width}l{length}", f"{width} mm continuous x {length} mm", width, length
    for width, height in DIECUT_SIZES:
        yield f"d{width}x{height}", f"{width} x {height} mm die-cut", width, height


def generate() -> str:
    version = (ROOT / "VERSION").read_text(encoding="ascii").strip()
    sizes = list(media())
    lines = [
        '*PPD-Adobe: "4.3"',
        '*% Generated by scripts/generate_ppd.py. Edit the generator, then regenerate.',
        '*FormatVersion: "4.3"',
        f'*FileVersion: "{version}"',
        '*LanguageVersion: English',
        '*LanguageEncoding: ISOLatin1',
        '*PCFileName: "QL580NNT.PPD"',
        '*Manufacturer: "Brother"',
        '*Product: "(Brother QL-580N)"',
        '*ModelName: "QL-580N macOS Driver"',
        '*ShortNickName: "QL-580N macOS Driver"',
        '*NickName: "QL-580N macOS Driver CUPS Raster"',
        '*1284DeviceID: "MFG:Brother;MDL:QL-580N;"',
        f'*APPrinterIconPath: "{ICON}"',
        '*cupsVersion: 1.2',
        '*cupsManualCopies: True',
        '*cupsSNMPStatus: True',
        f'*cupsFilter: "application/vnd.cups-raster 0 {FILTER}"',
        '*ColorDevice: False',
        '*DefaultColorSpace: Gray',
        '*FileSystem: False',
        '*LanguageLevel: "3"',
        '*Throughput: "20"',
        '*VariablePaperSize: True',
        '*LandscapeOrientation: Plus90',
        '*TTRasterizer: Type42',
        '*PSVersion: "(3010.000) 0"',
        '*OpenGroup: LabelSettings/Label Settings',
        '*OpenUI *Resolution/Resolution: PickOne',
        '*OrderDependency: 10 AnySetup *Resolution',
        '*DefaultResolution: 300x600dpi',
        '*Resolution 300dpi/300 DPI: "<</HWResolution[300 300]>>setpagedevice"',
        '*Resolution 300x600dpi/300 x 600 DPI (fine): "<</HWResolution[300 600]>>setpagedevice"',
        '*CloseUI: *Resolution',
        '*OpenUI *ColorModel/Color Mode: PickOne',
        '*OrderDependency: 11 AnySetup *ColorModel',
        '*DefaultColorModel: Gray',
        '*ColorModel Gray/8-bit Grayscale: "<</cupsColorSpace 0/cupsColorOrder 0/cupsBitsPerColor 8/cupsPreferredBitsPerColor 8>>setpagedevice"',
        '*CloseUI: *ColorModel',
        '*OpenUI *PageSize/Label Size: PickOne',
        '*OrderDependency: 20 AnySetup *PageSize',
        f'*DefaultPageSize: {DEFAULT_SIZE}',
    ]
    for name, label, width, height in sizes:
        lines.append(f'*PageSize {name}/{label}: "<</PageSize[{points(width)} {points(height)}]/ImagingBBox null>>setpagedevice"')
    lines.extend(('*CloseUI: *PageSize',
                  '*% Custom sizes are for continuous rolls; the filter checks supported widths.',
                  f'*MaxMediaWidth: "{points(62)}"',
                  f'*MaxMediaHeight: "{points(1000)}"',
                  f'*HWMargins: "{points(dots_mm(18))} {points(dots_mm(35))} {points(dots_mm(18))} {points(dots_mm(35))}"',
                  '*CustomPageSize True: "pop pop pop <</PageSize[5 -2 roll]/ImagingBBox null>>setpagedevice"',
                  f'*ParamCustomPageSize Width: 1 points {points(12)} {points(62)}',
                  f'*ParamCustomPageSize Height: 2 points {points(19)} {points(1000)}',
                  '*ParamCustomPageSize WidthOffset: 3 points 0 0',
                  '*ParamCustomPageSize HeightOffset: 4 points 0 0',
                  '*ParamCustomPageSize Orientation: 5 int 0 0',
                  '*OpenUI *PageRegion/Label Size: PickOne',
                  '*OrderDependency: 20 AnySetup *PageRegion',
                  f'*DefaultPageRegion: {DEFAULT_SIZE}'))
    for name, label, width, height in sizes:
        lines.append(f'*PageRegion {name}/{label}: "<</PageSize[{points(width)} {points(height)}]/ImagingBBox null>>setpagedevice"')
    lines.extend(('*CloseUI: *PageRegion', f'*DefaultImageableArea: {DEFAULT_SIZE}'))
    for name, label, width, height in sizes:
        lateral = dots_mm(23 if name.startswith('w54l') else 18)
        lower = dots_mm(35)
        box = (points(lateral), points(lower),
               points(Decimal(width) - lateral), points(Decimal(height) - lower))
        lines.append(f'*ImageableArea {name}/{label}: "{" ".join(box)}"')
    lines.append(f'*DefaultPaperDimension: {DEFAULT_SIZE}')
    for name, label, width, height in sizes:
        lines.append(f'*PaperDimension {name}/{label}: "{points(width)} {points(height)}"')
    lines.extend((
                  '*OpenUI *QLMedia/Roll Selection: PickOne',
                  '*OrderDependency: 30 AnySetup *QLMedia',
                  '*DefaultQLMedia: Manual',
                  '*QLMedia Auto/Automatic (fit to loaded roll): ""',
                  '*QLMedia Manual/Use selected paper size: ""',
                  '*CloseUI: *QLMedia',
                  '*OpenUI *QLStatus/Printer Status: PickOne',
                  '*OrderDependency: 30 AnySetup *QLStatus',
                  '*DefaultQLStatus: On',
                  '*QLStatus On/Check errors and confirm completion: ""',
                  '*QLStatus Off/Offline conversion (manual roll only): ""',
                  '*CloseUI: *QLStatus',
                  '*OpenUI *AutoCut/Automatic Cut: PickOne',
                  '*OrderDependency: 30 AnySetup *AutoCut',
                  '*DefaultAutoCut: On',
                  '*AutoCut On/On: ""',
                  '*AutoCut Off/Off: ""',
                  '*CloseUI: *AutoCut',
                  '*OpenUI *QLTrim/Trim Blank Space (continuous rolls): PickOne',
                  '*OrderDependency: 30 AnySetup *QLTrim',
                  '*DefaultQLTrim: Off',
                  '*QLTrim Off/Off (keep selected length): ""',
                  '*QLTrim On/On (trim top and bottom): ""',
                  '*CloseUI: *QLTrim',
                  '*OpenUI *QLHalftone/Halftone: PickOne',
                  '*OrderDependency: 31 AnySetup *QLHalftone',
                  '*DefaultQLHalftone: Ordered',
                  '*QLHalftone Ordered/Ordered: ""',
                  '*QLHalftone Threshold/Threshold: ""',
                  '*CloseUI: *QLHalftone',
                  '*CloseGroup: LabelSettings',
                  '*cupsIPPReason com.brother.ql580n-cutter-jam/Cutter jam. Clear the cutter before printing.: ""',
                  '*cupsIPPReason com.brother.ql580n-status-unavailable/Printer status unavailable. Check network and SNMP.: ""',
                  '*cupsIPPReason com.brother.ql580n-completion-unknown/Print completion unconfirmed. Check labels before resubmitting.: ""',
                  ''))
    return '\n'.join(lines)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate(), encoding='ascii')
    print(OUTPUT)


if __name__ == '__main__':
    main()
